package part01;

import java.util.ArrayList;

/**
 * @author F1shG3ck0
 */
/*
 * Object Class - the instances hold sorted searched data
 */
public class ImageAlbum {
	// private instance data
	// every new array must be searched starting with the first value (if there is
	// one)
	private int currentIndex = -1;
	// create an array list to store incoming sorted date containing the correct
	// data
	private ArrayList<ImageRecord> dateSorted = new ArrayList<ImageRecord>();
	// An instance of this class will be generated by an ImageManager as a result of
	// a search and will
	// be responsible for a collection of ImageRecord instances. All ImageRecords
	// managed by an ImageAlbum object should be
	// held in date order (earliest first) and should be accessed using the
	// following methods:

	/**
	 * Constructor Method
	 * 
	 * @param sorted
	 */
	public ImageAlbum(ArrayList<ImageRecord> sorted) {
		// add new ArrayList to instance array list
		this.dateSorted = new ArrayList<>(sorted);
	}

	/**
	 * Method to get the first reference to an Image record from the date sorted
	 * array list and return it. (if empty return null)
	 * 
	 * @return
	 */
	public ImageRecord getFirst() {
		// returns a reference to an ImageRecod instance – the first or ‘earliest’ image
		// in an ImageAlbum or null if there are no images in the album.
		// check for a first value (size is at least 1)
		if (dateSorted.size() > 0) {
			// new ImageRecord variable current to store the first reference from dateSorted
			ImageRecord current = dateSorted.get(0);
			// change currentIndex (now 0 as index 0 has been searched)
			currentIndex = 0;
			// return ImageRecord object
			return current;
		}
		// else return null (empty array list)
		return null;
	}

	/**
	 * Method to get the next reference to an Image record from the date sorted
	 * array list using currentIndex variable and return it. (if no next return null)
	 * 
	 * @return
	 */
	public ImageRecord getNext() {
		// returns a reference to an ImageRecord instance – the image ‘next’ to the
		// last image accessed – or null if no images in the album or no ‘next’ image
		// exists or no images previously accessed.
		// check for empty array list and size being at least 2 larger than the
		// currentIndex (working with indexing 0 - length-1)
		if (currentIndex != -1 && dateSorted.size() - 1 > currentIndex) {
			// increment currentIndex - to work on this index
			currentIndex++;
			// new ImageRecord variable current to store the reference at index currentIndex
			// from dateSorted
			ImageRecord current = dateSorted.get(currentIndex);
			// return ImageRecord object
			return current;
		}
		// else return null (at the end of array list)
		return null;
	}

	/**
	 * Method to get the previous reference to an Image record from the date sorted
	 * array list using currentIndex variable and return it. (if no previous return
	 * null)
	 * 
	 * @return
	 */
	public ImageRecord getPrevious() {
		// returns a reference to an ImageRecord instance – the image ‘previous’
		// to the last image accessed - or null if no images in the album or no
		// ‘previous’ image exists or no images previously
		// accessed.
		// check for empty array list, having accessed no images and making sure
		// currentIndex is not currently 0.
		if (dateSorted.size() > 0 && currentIndex != -1 && currentIndex > 0) {
			// decrement currentIndex - to work on this index
			currentIndex--;
			// new ImageRecord variable current to store the reference at index currentIndex
			// from dateSorted
			ImageRecord current = dateSorted.get(currentIndex);
			// return ImageRecord object
			return current;
		}
		// else return null (already at the beginning of array list /is empty)
		return null;

	}
	
	/**
	 * Method to find the collection size and return it
	 * @return
	 */
	public int getCollectionSize() {
	    return dateSorted.size();
	}

}
